import type { AccountData } from '@/data/mockDashboardData';

export const EMPTY_ACCOUNT_DATA: AccountData = {
  id: '',
  name: '—',
  size: 0,
  plan: 'Standard',
  planType: 'Standard',
  stage: 'Evaluation',
  status: 'Active',
  startingBalance: 0,
  profitTarget: 0,
  maxDrawdown: 0,
  dailyLossLimit: 0,
  currentBalance: 0,
  closedPnL: 0,
  drawdownUsed: 0,
  metrics: {
    winRate: 0,
    avgWin: 0,
    avgLoss: 0,
    bestDay: 0,
    worstDay: 0,
    tradingDays: 0,
    totalDays: 30,
    profitStreak: 0,
    grossProfit: 0,
    grossLoss: 0,
  },
  sessionPerformance: {
    preMarket: 0,
    morning: 0,
    lunch: 0,
    afternoon: 0,
  },
  dayOfWeekPerformance: {
    Mon: 0,
    Tue: 0,
    Wed: 0,
    Thu: 0,
    Fri: 0,
  },
  streaks: {
    maxWinStreak: 0,
    maxLossStreak: 0,
    currentStreak: 0,
  },
  equityHistory: [],
  dailyPnL: [],
  closedTrades: [],
};
